/**
 * Pengo static-site build helper, Node 20+, no dependencies or server.
 * Copy this file to .pengo/build.mjs in the CUSTOMER repository.
 * Run: node .pengo/build.mjs --source . --output .pengo-build
 * Netlify publish directory: .pengo-build. Existing customer files remain untouched.
 * For SvelteKit/Astro use the JSON contract directly instead of this static copier.
 */
import { createHash } from 'node:crypto';
import { readFile, readdir, mkdir, writeFile, copyFile, lstat, realpath } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const hash = (value) => createHash('sha256').update(value).digest('hex');
const escape = (value) =>
	String(value ?? '').replace(
		/[&<>"']/g,
		(c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]
	);
const exists = async (file) => {
	try {
		await lstat(file);
		return true;
	} catch (e) {
		if (e.code === 'ENOENT') return false;
		throw e;
	}
};
function normalizeManifest(value) {
	if (
		Object.keys(value).sort().join(',') !==
			'assetPath,blogPath,branch,format,siteId,siteUrl,version' ||
		value.version !== 1 ||
		value.format !== 'pengo-json-v1' ||
		!/^[A-Za-z0-9_-]{1,128}$/.test(value.siteId) ||
		!/^\/(?:[a-z0-9_-]+\/)+$/.test(value.blogPath) ||
		value.assetPath !== '/pengo-media/' ||
		!/^[A-Za-z0-9_-]+(?:\/[A-Za-z0-9_-]+)*$/.test(value.branch)
	)
		throw new Error('Invalid .pengo/config.json');
	const url = new URL(value.siteUrl);
	if (
		url.protocol !== 'https:' ||
		url.username ||
		url.password ||
		url.pathname !== '/' ||
		url.search ||
		url.hash
	)
		throw new Error('Use the canonical HTTPS website origin.');
	return {
		version: 1,
		siteId: value.siteId,
		siteUrl: value.siteUrl,
		branch: value.branch,
		blogPath: value.blogPath,
		assetPath: value.assetPath,
		format: value.format
	};
}
async function regular(file, max = 3_000_000) {
	const stat = await lstat(file);
	if (!stat.isFile() || stat.isSymbolicLink() || stat.size > max)
		throw new Error(`Unsafe or oversized publishing file: ${path.basename(file)}`);
	return readFile(file);
}
async function ensureNoSymlink(root, relative) {
	let target = root;
	for (const segment of relative.split('/').filter(Boolean)) {
		if (segment === '.' || segment === '..') throw new Error('Unsafe publishing path');
		target = path.join(target, segment);
		if ((await exists(target)) && (await lstat(target)).isSymbolicLink())
			throw new Error('Publishing paths may not contain symlinks');
	}
}
export function articleBody(article) {
	return `<div data-pengo-article="${escape(article.articleId)}" data-pengo-version="${escape(article.articleVersionId)}" data-pengo-hash="${escape(article.contentHash)}">${article.contentHtml}</div>`;
}
export function renderArticle(article, manifest, template) {
	const head = `<title>${escape(article.seoTitle ?? article.title)}</title>\n<meta name="description" content="${escape(article.description ?? article.excerpt)}">\n<link rel="canonical" href="${escape(article.url)}">\n<meta property="og:title" content="${escape(article.title)}">\n<meta property="og:url" content="${escape(article.url)}">\n<script type="application/ld+json">${JSON.stringify({ '@context': 'https://schema.org', '@type': 'Article', headline: article.title, url: article.url, datePublished: new Date(article.publishedAt).toISOString(), dateModified: new Date(article.modifiedAt).toISOString(), ...(article.image ? { image: new URL(manifest.assetPath + article.image.filename, manifest.siteUrl).href } : {}) }).replace(/</g, '\\u003c')}</script>`;
	const body = `<article><h1>${escape(article.title)}</h1>${article.image ? `<img src="${manifest.assetPath}${article.image.filename}" alt="${escape(article.image.alt)}" width="1200" style="max-width:100%;height:auto">` : ''}${articleBody(article)}</article>`;
	// Templates are CUSTOMER-owned code, never generated by the article writer.
	for (const token of ['<!-- PENGO_HEAD -->', '<!-- PENGO_BODY -->'])
		if (template.split(token).length !== 2)
			throw new Error(`Article template needs exactly one ${token}`);
	return template
		.replace('<!-- PENGO_HEAD -->', head)
		.replace('<!-- PENGO_BODY -->', body)
		.replace(/<html\b([^>]*)>/i, (tag, attributes) =>
			article.locale && !/\blang\s*=/i.test(attributes)
				? `<html${attributes} lang="${escape(article.locale)}">`
				: tag
		);
}
const DEFAULT_TEMPLATE =
	'<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><!-- PENGO_HEAD --><style>body{max-width:760px;margin:3rem auto;padding:0 1.25rem;font:18px/1.7 system-ui;color:#18231e}a{color:#17633a}h1{line-height:1.15}img{max-width:100%;height:auto}[data-oros-cta-id]{display:inline-block;padding:.7em 1.1em;background:#17633a;color:white;border-radius:.35em;font-weight:600;text-decoration:none}</style></head><body><nav><a href="/">← Home</a></nav><!-- PENGO_BODY --></body></html>';
/** Build into a NEW directory. Never edit source files or replace foreign routes. */
export async function buildStaticSite({
	root = process.cwd(),
	source = '.',
	output = '.pengo-build'
} = {}) {
	root = path.resolve(root);
	if (
		path.isAbsolute(source) ||
		path.isAbsolute(output) ||
		[source, output].some((v) => v.split(/[\\/]/).includes('..')) ||
		output === '.' ||
		output === ''
	)
		throw new Error('Source/output must be safe relative paths.');
	const sourceDir = path.resolve(root, source),
		out = path.resolve(root, output);
	if (sourceDir === out || (await exists(out)))
		throw new Error('Use a new empty build directory; no existing directory will be overwritten.');
	await ensureNoSymlink(root, source === '.' ? '' : source);
	await ensureNoSymlink(root, '.pengo/config.json');
	const manifest = normalizeManifest(
		JSON.parse(await regular(path.join(root, '.pengo/config.json')))
	);
	await mkdir(out, { recursive: true });
	// Static public assets only. Never copy credentials, source maps, dotfolders,
	// package metadata or server source from the customer repository.
	const publicExtension =
		/\.(?:html|css|js|png|jpe?g|gif|webp|avif|svg|ico|woff2?|ttf|pdf|xml|txt)$/i;
	async function copyPublic(from, to) {
		for (const entry of await readdir(from, { withFileTypes: true })) {
			if (
				entry.name.startsWith('.') ||
				['node_modules', 'connectors', 'scripts'].includes(entry.name)
			)
				continue;
			const src = path.join(from, entry.name),
				dest = path.join(to, entry.name);
			if (src === out) continue;
			if (entry.isSymbolicLink())
				throw new Error('Static source contains a symlink; review the public file set.');
			if (entry.isDirectory()) {
				await mkdir(dest, { recursive: true });
				await copyPublic(src, dest);
			} else if (
				entry.isFile() &&
				(publicExtension.test(entry.name) || ['_redirects', '_headers'].includes(entry.name))
			)
				await copyFile(src, dest);
		}
	}
	await copyPublic(sourceDir, out);
	const manifestHash = hash(JSON.stringify(manifest));
	const articleDir = path.join(root, '.pengo/articles');
	await ensureNoSymlink(root, '.pengo/articles');
	const files = (await exists(articleDir)) ? await readdir(articleDir) : [];
	if (files.length > 2000) throw new Error('Too many articles for this build helper.');
	const articles = [];
	let template = DEFAULT_TEMPLATE;
	if (await exists(path.join(root, '.pengo/template.html')))
		template = String(await regular(path.join(root, '.pengo/template.html')));
	for (const file of files.sort()) {
		if (!/^[a-z0-9]+(?:-[a-z0-9]+)*\.json$/.test(file))
			throw new Error('Unexpected file in article directory.');
		const article = JSON.parse(await regular(path.join(articleDir, file)));
		const { contentHash, ...data } = article;
		if (
			article.version !== 1 ||
			!/^[a-f0-9]{64}$/.test(contentHash) ||
			hash(JSON.stringify(data)) !== contentHash ||
			article.siteId !== manifest.siteId ||
			`${article.slug}.json` !== file ||
			article.url !== new URL(`${manifest.blogPath}${article.slug}/`, manifest.siteUrl).href ||
			typeof article.contentHtml !== 'string'
		)
			throw new Error('Article identity or content integrity check failed.');
		const route = path.join(out, manifest.blogPath.slice(1), article.slug);
		if (await exists(route))
			throw new Error(`Existing customer route would be overwritten: ${article.slug}`);
		if (article.image) {
			const filename = article.image.filename;
			if (!/^[a-f0-9]{64}\.(png|jpg|webp)$/.test(filename)) throw new Error('Invalid image path');
			await ensureNoSymlink(root, '.pengo/assets/' + filename);
			const bytes = await regular(path.join(root, '.pengo/assets', filename), 5_000_000);
			if (hash(bytes) !== filename.split('.')[0])
				throw new Error('Article image integrity check failed');
			const asset = path.join(out, manifest.assetPath, filename);
			if ((await exists(asset)) && hash(await readFile(asset)) !== hash(bytes))
				throw new Error('Foreign image collision');
			await mkdir(path.dirname(asset), { recursive: true });
			await writeFile(asset, bytes);
		}
		await mkdir(route, { recursive: true });
		await writeFile(path.join(route, 'index.html'), renderArticle(article, manifest, template));
		articles.push(article);
	}
	articles.sort((a, b) => b.publishedAt - a.publishedAt);
	const listing = `<section data-pengo-list><ul>${articles.map((a) => `<li><a href="${escape(a.url)}">${escape(a.title)}</a>${a.excerpt ? `<p>${escape(a.excerpt)}</p>` : ''}</li>`).join('')}</ul></section>`;
	const index = path.join(out, manifest.blogPath, 'index.html');
	await mkdir(path.dirname(index), { recursive: true });
	if (await exists(index)) {
		const old = String(await regular(index));
		if (old.split('<!-- PENGO_ARTICLES -->').length !== 2)
			throw new Error(
				'Existing blog index needs one <!-- PENGO_ARTICLES --> insertion marker. Existing content was not replaced.'
			);
		await writeFile(index, old.replace('<!-- PENGO_ARTICLES -->', listing));
	} else
		await writeFile(
			index,
			`<!doctype html><html><head><meta charset="utf-8"><title>Articles</title><link rel="canonical" href="${escape(new URL(manifest.blogPath, manifest.siteUrl).href)}"></head><body><a href="/">Home</a><h1>Articles</h1>${listing}</body></html>`
		);
	const sitemap = path.join(out, 'pengo-sitemap.xml');
	if (await exists(sitemap))
		throw new Error('pengo-sitemap.xml already exists in customer source.');
	await writeFile(
		sitemap,
		`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${articles.map((a) => `<url><loc>${escape(a.url)}</loc><lastmod>${new Date(a.modifiedAt).toISOString()}</lastmod></url>`).join('')}</urlset>`
	);
	const robots = path.join(out, 'robots.txt');
	const existingRobots = (await exists(robots)) ? String(await regular(robots)) : '';
	await writeFile(
		robots,
		`${existingRobots}\nSitemap: ${new URL('/pengo-sitemap.xml', manifest.siteUrl).href}\n`
	);
	const proofDir = path.join(out, '.well-known');
	await mkdir(proofDir, { recursive: true });
	await writeFile(
		path.join(proofDir, 'pengo.json'),
		JSON.stringify({ version: 1, siteId: manifest.siteId, manifestHash })
	);
	return { output: out, articles: articles.length };
}
if (process.argv[1] && (await realpath(process.argv[1]).catch(() => null)) === fileURLToPath(import.meta.url)) {
	const args = process.argv.slice(2);
	if (args.length !== 4 || args[0] !== '--source' || args[2] !== '--output')
		throw new Error('Usage: node .pengo/build.mjs --source . --output .pengo-build');
	console.log(await buildStaticSite({ source: args[1], output: args[3] }));
}
